server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
  security:
    filter:
      order: 0

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.pharmasys: DEBUG 